# Generated by Selenium IDE
import pytest
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import WebDriverException
import sys

class TestUserlogin():
    def setup_method(self, method):
        print("\n\033[94m=== Starting User Login Test ===\033[0m")  # Blue color
        try:
            self.driver = webdriver.Chrome()
            print("\033[92m✓ Browser initialized successfully\033[0m")  # Green color
        except WebDriverException as e:
            print(f"\033[91m✗ Failed to initialize browser: {str(e)}\033[0m")  # Red color
            raise
        self.vars = {}
  
    def teardown_method(self, method):
        try:
            self.driver.quit()
            print("\033[92m✓ Browser closed successfully\033[0m")
        except Exception as e:
            print(f"\033[91m✗ Failed to close browser: {str(e)}\033[0m")
        print("\033[94m=== User Login Test Completed ===\033[0m")
  
    def test_userlogin(self):
        try:
            # Navigate to homepage
            self.driver.get("http://127.0.0.1:8000/")
            print("\033[92m✓ Navigated to homepage\033[0m")
            
            # Set window size
            self.driver.set_window_size(1552, 832)
            print("\033[92m✓ Window size set\033[0m")
            
            # Click login link
            self.driver.find_element(By.LINK_TEXT, "Login").click()
            print("\033[92m✓ Clicked login link\033[0m")
            
            # Enter email
            email_field = self.driver.find_element(By.ID, "email")
            email_field.click()
            email_field.send_keys("affair-veal-ovary@duck.com")
            print("\033[92m✓ Entered email\033[0m")
            
            # Enter password
            password_field = self.driver.find_element(By.ID, "password")
            password_field.send_keys("Jobzz@6544")
            print("\033[92m✓ Entered password\033[0m")
            
            # Click login button
            self.driver.find_element(By.CSS_SELECTOR, "button").click()
            print("\033[92m✓ Clicked login button\033[0m")
            
            # Wait for login to complete and verify success
            try:
                logout_link = WebDriverWait(self.driver, 10).until(
                    EC.presence_of_element_located((By.LINK_TEXT, "Logout"))
                )
                print("\033[92m✓ Login successful - Logout link found\033[0m")
                
                # Click logout
                logout_link.click()
                print("\033[92m✓ Clicked logout\033[0m")
                
                # Wait for logout to complete
                WebDriverWait(self.driver, 10).until(
                    EC.presence_of_element_located((By.LINK_TEXT, "Login"))
                )
                print("\033[92m✓ Logout successful - Login link found\033[0m")
                
                print("\n\033[92m✓ TEST PASSED: User login and logout completed successfully\033[0m")
                
            except Exception as e:
                print(f"\033[91m✗ Login verification failed: {str(e)}\033[0m")
                raise
                
        except Exception as e:
            print(f"\n\033[91m✗ TEST FAILED: {str(e)}\033[0m")
            # Take screenshot on failure
            timestamp = time.strftime("%Y%m%d-%H%M%S")
            self.driver.save_screenshot(f'test_failure_{timestamp}.png')
            print(f"\033[93mScreenshot saved as test_failure_{timestamp}.png\033[0m")
            raise

def run_test():
    """Function to run the test and handle exceptions"""
    test = TestUserlogin()
    try:
        test.setup_method(None)
        test.test_userlogin()
        return True
    except Exception as e:
        print(f"\n\033[91mTest execution failed: {str(e)}\033[0m")
        return False
    finally:
        test.teardown_method(None)

if __name__ == "__main__":
    success = run_test()
    if success:
        print("\n\033[92mAll tests completed successfully!\033[0m")
        sys.exit(0)
    else:
        print("\n\033[91mTest execution failed!\033[0m")
        sys.exit(1)

