# Generated by Django 5.0.7 on 2024-10-13 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_initial'),
        ('vendor', '0011_rename_rental_price_to_rental_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='vendor.vehicle'),
        ),
    ]
