# Generated by Django 5.0.7 on 2024-11-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='vendor_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
