# Generated by Django 5.0.7 on 2025-03-14 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_vehiclelocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclelocation',
            name='accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclelocation',
            name='battery_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclelocation',
            name='is_moving',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='vehiclelocation',
            index=models.Index(fields=['booking', '-timestamp'], name='vehicle_loc_booking_edeb11_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclelocation',
            index=models.Index(fields=['timestamp'], name='vehicle_loc_timesta_810bb5_idx'),
        ),
        migrations.AlterModelTable(
            name='vehiclelocation',
            table='vehicle_locations',
        ),
    ]
