# Generated by Django 5.0.7 on 2024-11-02 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_booking_platform_fee_booking_vendor_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='platform_fee',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='vendor_amount',
        ),
    ]
