# Generated by Django 5.0.7 on 2025-03-14 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_vehiclelocation_accuracy_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VehicleLocation',
        ),
    ]
