# Generated by Django 5.0.7 on 2025-04-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_delete_vehiclelocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='early_return_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='early_return_otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='early_return_requested',
            field=models.BooleanField(default=False),
        ),
    ]
