# Generated by Django 5.0.7 on 2025-04-05 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_booking_early_return_otp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='early_return_otp',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='early_return_otp_created_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='early_return_requested',
        ),
    ]
