# Generated by Django 5.0.7 on 2025-04-05 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_locationshare_is_live_tracking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationshare',
            name='is_live_tracking',
        ),
    ]
