# Generated by Django 5.0.7 on 2025-04-05 20:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_remove_locationshare_is_live_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationshare',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
