# Generated by Django 5.0.7 on 2025-04-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_alter_locationshare_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationshare',
            name='is_live_tracking',
            field=models.BooleanField(default=False),
        ),
    ]
