# Generated by Django 5.0.7 on 2025-04-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_locationshare_is_live_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationshare',
            name='accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
