# Generated by Django 5.0.7 on 2025-04-07 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_locationshare_accuracy'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='has_submitted_vehicle_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='refund_status',
            field=models.CharField(choices=[('not_refunded', 'Not Refunded'), ('refunded', 'Refunded'), ('failed', 'Refund Failed'), ('not_applicable', 'Not Applicable')], default='not_refunded', max_length=20),
        ),
        migrations.CreateModel(
            name='VehicleReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('all_clear', 'All Clear'), ('complaint', 'Has Complaint')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_report', to='mainapp.booking')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_area', models.CharField(choices=[('engine', 'Engine/Transmission'), ('brakes', 'Brakes/Steering'), ('lights', 'Lights/Electrical'), ('ac_heater', 'AC/Heater'), ('interior', 'Interior Condition'), ('exterior', 'Exterior Condition/Damage'), ('tires', 'Tires'), ('cleaning', 'Cleanliness'), ('fuel', 'Fuel Level Issue'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, help_text='Please provide details about the complaint.')),
                ('vehicle_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='mainapp.vehiclereport')),
            ],
        ),
    ]
