# Generated by Django 5.0.7 on 2025-04-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_booking_has_submitted_vehicle_report_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclereport',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='has_submitted_vehicle_report',
        ),
        migrations.AlterField(
            model_name='booking',
            name='refund_status',
            field=models.CharField(choices=[('not_refunded', 'Not Refunded'), ('refunded', 'Refunded'), ('failed', 'Refund Failed')], default='not_refunded', max_length=20),
        ),
        migrations.DeleteModel(
            name='ComplaintDetail',
        ),
        migrations.DeleteModel(
            name='VehicleReport',
        ),
    ]
