# Generated by Django 5.0.7 on 2025-02-18 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('mainapp', '0001_initial'),
        ('vendor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_drivers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driverapplicationlog',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driverapplicationlog',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.driver'),
        ),
        migrations.AddField(
            model_name='driver',
            name='auth',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drivers.driverauth'),
        ),
        migrations.AddField(
            model_name='driverbooking',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.booking'),
        ),
        migrations.AddField(
            model_name='driverbooking',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_bookings', to='drivers.driver'),
        ),
        migrations.AddField(
            model_name='driverbooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driverdocument',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='drivers.driver'),
        ),
        migrations.AddField(
            model_name='driverreview',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driverreview',
            name='driver_booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='drivers.driverbooking'),
        ),
        migrations.AddField(
            model_name='driverschedule',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='drivers.driver'),
        ),
        migrations.AddField(
            model_name='drivertrip',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.booking'),
        ),
        migrations.AddField(
            model_name='drivertrip',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='drivers.driver'),
        ),
        migrations.AddField(
            model_name='drivervehicleassignment',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_assignments', to='drivers.driver'),
        ),
        migrations.AddField(
            model_name='drivervehicleassignment',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_assignments', to='vendor.vehicle'),
        ),
        migrations.AlterUniqueTogether(
            name='driverdocument',
            unique_together={('driver', 'document_type')},
        ),
        migrations.AlterUniqueTogether(
            name='driverreview',
            unique_together={('driver_booking', 'created_by')},
        ),
        migrations.AlterUniqueTogether(
            name='driverschedule',
            unique_together={('driver', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='drivervehicleassignment',
            unique_together={('driver', 'vehicle', 'is_active')},
        ),
    ]
