# Generated by Django 5.0.7 on 2025-02-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdocument',
            name='document',
            field=models.FileField(upload_to='driver_documents/'),
        ),
        migrations.AlterField(
            model_name='driverdocument',
            name='document_type',
            field=models.CharField(choices=[('license', "Driver's License"), ('insurance', 'Insurance'), ('registration', 'Vehicle Registration'), ('other', 'Other')], max_length=20),
        ),
    ]
