# Generated by Django 5.0.7 on 2025-02-19 04:23

import django.db.models.deletion
import drivers.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_alter_driverdocument_document_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdocument',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverdocument',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='driverdocument',
            name='document',
            field=models.FileField(upload_to=drivers.models.driver_document_path),
        ),
        migrations.AlterField(
            model_name='driverdocument',
            name='document_type',
            field=models.CharField(choices=[('license', 'Driver License'), ('identity', 'Identity Proof'), ('address', 'Address Proof')], max_length=20),
        ),
    ]
