# Generated by Django 5.0.7 on 2025-02-19 16:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_driverdocument_verified_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driverbooking',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='driverbooking',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='driverbooking',
            name='booking_date',
        ),
        migrations.RemoveField(
            model_name='driverbooking',
            name='booking_type',
        ),
        migrations.RemoveField(
            model_name='driverbooking',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='driverbooking',
            name='start_time',
        ),
        migrations.AddField(
            model_name='driverbooking',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 19, 16, 26, 38, 696924, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driverbooking',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 19, 16, 26, 53, 700624, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driverbooking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='driverbooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
