# Generated by Django 5.0.7 on 2025-03-14 06:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0005_alter_driverbooking_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverbooking',
            name='booking_type',
            field=models.CharField(choices=[('full_day', 'Full Day'), ('point_to_point', 'Point to Point')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driverbooking',
            name='distance',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='driverbooking',
            name='dropoff_lat',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='driverbooking',
            name='dropoff_lng',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='driverbooking',
            name='dropoff_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='driverbooking',
            name='pickup_lat',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='driverbooking',
            name='pickup_lng',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='driverbooking',
            name='pickup_location',
            field=models.CharField(default=555, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driverbooking',
            name='rate_per_km',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='drivertrip',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trip', to='drivers.driverbooking'),
        ),
        migrations.AlterField(
            model_name='drivertrip',
            name='end_location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
