# Generated by Django 5.0.7 on 2025-03-15 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0006_driverbooking_booking_type_driverbooking_distance_and_more'),
        ('mainapp', '0005_delete_vehiclelocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverbooking',
            name='booking_type',
        ),
        migrations.RemoveField(
            model_name='driverbooking',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='driverbooking',
            name='dropoff_lat',
        ),
        migrations.RemoveField(
            model_name='driverbooking',
            name='dropoff_lng',
        ),
        migrations.RemoveField(
            model_name='driverbooking',
            name='dropoff_location',
        ),
        migrations.RemoveField(
            model_name='driverbooking',
            name='pickup_lat',
        ),
        migrations.RemoveField(
            model_name='driverbooking',
            name='pickup_lng',
        ),
        migrations.RemoveField(
            model_name='driverbooking',
            name='pickup_location',
        ),
        migrations.RemoveField(
            model_name='driverbooking',
            name='rate_per_km',
        ),
        migrations.AlterField(
            model_name='drivertrip',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.booking'),
        ),
        migrations.AlterField(
            model_name='drivertrip',
            name='end_location',
            field=models.CharField(max_length=255),
        ),
    ]
