# Generated by Django 5.0.7 on 2025-03-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0007_remove_driverbooking_booking_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivertrip',
            name='end_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='drivertrip',
            name='end_otp_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drivertrip',
            name='end_otp_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='drivertrip',
            name='start_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='drivertrip',
            name='start_otp_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drivertrip',
            name='start_otp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
