# Generated by Django 5.0.7 on 2025-03-18 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0008_drivertrip_end_otp_drivertrip_end_otp_generated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivertrip',
            name='end_otp',
        ),
        migrations.RemoveField(
            model_name='drivertrip',
            name='end_otp_generated_at',
        ),
        migrations.RemoveField(
            model_name='drivertrip',
            name='end_otp_verified',
        ),
        migrations.RemoveField(
            model_name='drivertrip',
            name='start_otp',
        ),
        migrations.RemoveField(
            model_name='drivertrip',
            name='start_otp_generated_at',
        ),
        migrations.RemoveField(
            model_name='drivertrip',
            name='start_otp_verified',
        ),
    ]
