# Generated by Django 5.0.7 on 2025-03-18 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0009_remove_drivertrip_end_otp_and_more'),
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverbooking',
            name='booking_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverbooking',
            name='booking_type',
            field=models.CharField(choices=[('specific_date', 'Single Day Booking'), ('point_to_point', 'Point to Point Service'), ('with_vehicle', 'Booking with Driver Vehicle')], default='specific_date', max_length=20),
        ),
        migrations.AddField(
            model_name='driverbooking',
            name='drop_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='driverbooking',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverbooking',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='driverbooking',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='driverbooking',
            name='service_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverbooking',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverbooking',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendor.vehicle'),
        ),
        migrations.AlterField(
            model_name='driverbooking',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driverbooking',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
