# Generated by Django 5.0.7 on 2025-03-18 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0010_driverbooking_booking_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driverbooking',
            options={},
        ),
        migrations.RemoveField(
            model_name='driverbooking',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='driverbooking',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='driverbooking',
            name='service_date',
        ),
        migrations.AddField(
            model_name='driverbooking',
            name='distance',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='driverbooking',
            name='drop_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='driverbooking',
            name='drop_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='driverbooking',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='driverbooking',
            name='pickup_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='driverbooking',
            name='pickup_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='driverbooking',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='driverbooking',
            name='booking_type',
            field=models.CharField(choices=[('specific_date', 'Single Day Booking'), ('point_to_point', 'Point to Point Service'), ('with_vehicle', 'Book with Vehicle')], max_length=20),
        ),
        migrations.AlterField(
            model_name='driverbooking',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.driver'),
        ),
        migrations.AlterField(
            model_name='driverbooking',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driverbooking',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='driverbooking',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driverbooking',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterModelTable(
            name='driverbooking',
            table=None,
        ),
    ]
