# Generated by Django 5.0.7 on 2025-03-18 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0011_alter_driverbooking_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driverbooking',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='driverbooking',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='driverbooking',
            name='drop_latitude',
        ),
        migrations.RemoveField(
            model_name='driverbooking',
            name='drop_longitude',
        ),
        migrations.RemoveField(
            model_name='driverbooking',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='driverbooking',
            name='pickup_latitude',
        ),
        migrations.RemoveField(
            model_name='driverbooking',
            name='pickup_longitude',
        ),
        migrations.RemoveField(
            model_name='driverbooking',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='driverbooking',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='driverbooking',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='driverbooking',
            name='service_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driverbooking',
            name='booking_type',
            field=models.CharField(choices=[('specific_date', 'Single Day Booking'), ('point_to_point', 'Point to Point Service'), ('with_vehicle', 'Booking with Driver Vehicle')], default='specific_date', max_length=20),
        ),
        migrations.AlterField(
            model_name='driverbooking',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_bookings', to='drivers.driver'),
        ),
        migrations.AlterField(
            model_name='driverbooking',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driverbooking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='driverbooking',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driverbooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterModelTable(
            name='driverbooking',
            table='driver_booking',
        ),
    ]
