# Generated by Django 5.0.7 on 2025-03-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0012_alter_driverbooking_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverbooking',
            name='drop_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverbooking',
            name='drop_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverbooking',
            name='pickup_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverbooking',
            name='pickup_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
