# Generated by Django 5.0.7 on 2025-03-23 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0013_driverbooking_drop_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='blockchain_tx_hash',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
    ]
