# Generated by Django 5.0.7 on 2025-03-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0014_driver_blockchain_tx_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverapplicationlog',
            name='action',
            field=models.CharField(choices=[('approve', 'Approved'), ('reject', 'Rejected'), ('document_verify', 'Document Verified')], max_length=20),
        ),
    ]
