# Generated by Django 5.0.7 on 2025-03-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0015_alter_driverapplicationlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='blockchain_verified',
            field=models.BooleanField(default=False),
        ),
    ]
