# Generated by Django 5.0.7 on 2025-04-07 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0017_drivertrip_end_latitude_drivertrip_end_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivertrip',
            name='end_latitude',
        ),
        migrations.RemoveField(
            model_name='drivertrip',
            name='end_longitude',
        ),
        migrations.RemoveField(
            model_name='drivertrip',
            name='is_tracking_active',
        ),
        migrations.RemoveField(
            model_name='drivertrip',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='drivertrip',
            name='otp_verified',
        ),
        migrations.RemoveField(
            model_name='drivertrip',
            name='route_data',
        ),
        migrations.RemoveField(
            model_name='drivertrip',
            name='start_latitude',
        ),
        migrations.RemoveField(
            model_name='drivertrip',
            name='start_longitude',
        ),
        migrations.DeleteModel(
            name='DriverLocation',
        ),
    ]
