# Generated by Django 5.0.7 on 2025-04-07 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0018_remove_drivertrip_end_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivertrip',
            name='end_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drivertrip',
            name='end_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drivertrip',
            name='is_tracking_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='drivertrip',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='drivertrip',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='drivertrip',
            name='route_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drivertrip',
            name='start_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drivertrip',
            name='start_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DriverLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('accuracy', models.FloatField(default=0, help_text='Accuracy in meters')),
                ('speed', models.FloatField(blank=True, default=0, help_text='Speed in km/h', null=True)),
                ('heading', models.FloatField(blank=True, default=0, help_text='Heading in degrees', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_end_location', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='drivers.driver')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='drivers.drivertrip')),
            ],
            options={
                'verbose_name': 'Driver Location',
                'verbose_name_plural': 'Driver Locations',
                'ordering': ['-timestamp'],
            },
        ),
    ]
