# Generated by Django 5.0.7 on 2025-04-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0019_drivertrip_end_latitude_drivertrip_end_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivertrip',
            name='booking',
        ),
        migrations.AddField(
            model_name='drivertrip',
            name='booking_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
