# Generated by Django 5.0.7 on 2025-02-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('driver_approval', 'Driver Approval'), ('driver_rejection', 'Driver Rejection'), ('driver_suspension', 'Driver Suspension'), ('document_verification', 'Document Verification')], max_length=30)),
                ('action_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
